ReactiveBayes/RxInfer.jl

- src/inference.jl
- test/test_inference.jl
This PR fixes #23 & #24. Additionally this PR adds support for indexing operation on the RHS in the `@autoupdates` macro.
> Fix #23 & #24

- src/inference.jl
> add docs initmessage/initmarginas

- Makefile
- docs/src/contributing/overview.md
Same as https://github.com/biaslab/ReactiveMP.jl/pull/278
> convert testset to test_args

- docs/src/manuals/model-specification.md
> Docs: Add info on factor node creation using `Distributions.jl`

- README.md
> Fix README formulas

- examples/.meta.jl
- examples/Chance Constraints.ipynb
Demo based on (van de Laar et al., 2021, "Chance-constrained active inference")
and [discussion](https://discourse.julialang.org/t/use-of-update-in-rxinfer-to-handle-multiple-iterations) with John Boik.
> Add chance-constrained AIF demo

- paper/paper.bib
This PR fixes the DOI entry for one of the references used in the JOSS paper. https://github.com/openjournals/joss-reviews/issues/5161#issuecomment-1490603148
> paper: fix doi for the Julia paper

- CITATION.cff
- README.md
> add the CITATION.cff and a reference to the JOSS paper

- docs/src/contributing/new-example.md
- examples/Universal Mixtures.ipynb
> Fix equation rendering for mixture notebook

- docs/Project.toml
- docs/make.jl
- docs/src/index.md
- docs/src/manuals/delta-node.md
> Add manual for delta node

- examples/.meta.jl
Fixes weird font reported in https://github.com/biaslab/RxInfer.jl/issues/144
> Fix weird font in the examples section

- docs/src/library/bethe-free-energy.md
This branch includes an introduction to the Bethe Free Energy in the docs. Fixes #152 and #95.
> Introduce Bethe Free Energy

- .github/workflows/CI.yml
This PR changes CI to use Julia 1.10 for tests
> Use Julia 1.10 for tests

- src/inference.jl
This PR hopefully resolves #220
> Resolve #220

- .github/workflows/CI.yml
- src/constraints/form/form_point_mass.jl
> Use julia cache in CI

- examples/advanced_examples/Assessing People Skills.ipynb
This PR updates the Assessing People's Skills example for use of GraphPPL v4 as per [migration guide](https://reactivebayes.github.io/GraphPPL.jl/dev/migration_3_to_4/).
> fix: update the Assessing People's Skills example

- docs/make.jl
- docs/src/contributing/external-examples.md
This PR adds a section about examples that are outside of official documentation.
> Add external examples section

- .github/workflows/CI.yml
This PR changes the CI.yml to use setup-julia of version 2
> Use setup-julia version 2

- .github/workflows/CI.yml
Fixes https://github.com/ReactiveBayes/RxInfer.jl/issues/292
> Add CODECOV_TOKEN in CI

- README.md
This PR updates README to include the Dynalist link to our public meetings
> Add Dynalist link for public meetings

- README.md
This PR changes the README a bit to make the story a bit nicer
> Proof-read README

- test/models/mixtures/gamma_mixture_tests.jl
- test/models/mixtures/gmm_multivariate_tests.jl
- test/models/mixtures/gmm_univariate_tests.jl
This PR fixes some tests. I'm not completely sure why things changed, but it seems mostly because of the order in which message updates were done. Most tests showed small changes and in Gamma mixture model the FE is even better, but in the univariate gaussian mixture case, the free energy became worse. I tweaked the test because it was giving somewhat inconsistent results
> Fix broken tests

- README.md
This PR updates the roadmap and makes some minor changes to the README
> Update the roadmap

- README.md
This PR updates README and adds the recorded presentation from JuliaUserGroupMunich https://www.youtube.com/watch?v=KuluqEzFtm8
> add juliausergroupmunich video

- test/ext/ProjectionExt/inference_with_projection_tests.jl
Fixes tests for https://github.com/ReactiveBayes/ReactiveMP.jl/pull/413
> fix tests for RMP PR413

- Project.toml
> Bump projection deps

- docs/src/manuals/telemetry.md
- src/session.jl
- src/telemetry.jl
This is a small PR that adds a proxy behind the database and also adds RxInfer and Julia version running to the payload
> Update telemetry endpoint and add RxInfer version to logging

- src/model/plugins/reactivemp_inference.jl
- test/inference/inference_tests.jl
Added a fix and test for issue #318. 
Should I leave more information here?
> Allow for vector of inputs in `streaming inference`
