- src/inference.jl
- test/test_inference.jl
This PR adds more information and explanation about the `data` keyword argument in the `inference` function as well as for the `data` and `datastream` keyword arguments in the `rxinference` function. Fixes #18 .
> docs: add docstrings for the `data` arguments in the inference functions

- src/inference.jl
This PR implements a small TODO label, namely
- Now it is possible to use a vector of variable on the RHS of every expression in the  `@autoupdates` macro
Plus extra:
- Experimental and is subject to change, pass `Ref{Int}` as an argument to the number of iterations in the `rxinference` function in order to change number of iterations in real-time.
- Small fix for inference results postprocessing functionality
> Allow vector of variables as an argument in the `@autoupdates` macro

- src/graphppl.jl
Fix typo in documentation where NormalMeanPrecision was denoted as NormalMeanVariance
> Fix Typo in Documentation

- docs/src/assets/header.js
> docs(): fix broken 'edit' links for examples

- docs/src/library/functional-forms.md
- src/constraints/form/form_sample_list.jl
- test/constraints/form/test_form_sample_list.jl
- test/runtests.jl
> make the sample list form constraint more generic

- src/constraints/form/form_point_mass.jl
- test/constraints/form/test_form_point_mass.jl
Previously the PointMass form constraint called slow optimization routine for `<: Distribution` objects, even though it is easier and faster to return the `mode` of the distribution. This PR fixes that. Found by @bartvanerp
> fast path for dists in the PointMass constraint

- README.md
- docs/src/contributing/overview.md
I moved the PkgEval badge from README to the developers documentation. The badge does only confuse users, the failing badge does not indicate that there is a problem with RxInfer, but can also indicate a problem with some of its dependencies (which, in 99% if cases, it is a problem with the dependencies).
> Move pkgeval badge to the developers documentation

- examples/advanced_examples/Global Parameter Optimisation.ipynb
- examples/basic_examples/Kalman filtering and smoothing.ipynb
Closes #158 
I removed the table of content in two notebook, as the corresponding `<a></a>` tags did not nicely render in the docs.
> Fix rendering of subheaders in docs

- docs/make.jl
- docs/src/contributing/new-documentation.md
- docs/src/contributing/new-example.md
- docs/src/contributing/new-package.md
This PR moves the content of this [repo](https://github.com/biaslab/RxInferDevGuides.jl/tree/main) to the main documentation. The repo is not very well known, I will archive it as soon as the PR is merged.
> Add more contributing guides

- docs/make.jl
- docs/src/manuals/migration-guide-v2-v3.md
- src/model/model.jl
This PR adds more information to the migration guide and some extra hidden tests in the provided examples
> Add more information to the migration guide

- docs/src/manuals/getting-started.md
- docs/src/manuals/inference/initialization.md
- docs/src/manuals/inference/static.md
- docs/src/manuals/migration-guide-v2-v3.md
This PR makes the documentation for RxInfer better by:
- Moving important details about initializing nested models to the main guide. The migration guide now points to this main guide.
- Adding more info about how RxInfer handles missing values.
- Making some small fixes.
Fixes #298
> Update the documentation for the initialization syntax + minor fixes

- README.md
- docs/src/index.md
- docs/src/manuals/inference/initialization.md
- examples/basic_examples/Coin Toss Model.ipynb
To alleviate confusion experienced by new users and developers, I have removed Forney-style prefixes from the documentation and examples, retaining only “factor graph” for clarity.
> Remove Forney-style prefixes from documentation

- src/constraints/form/form_sample_list.jl
- test/constraints/form/form_sample_list_tests.jl
See #340 for an explanation for this PR
> add linearizedproductof to lowprioritycandidates for sample list form constraint

- .github/workflows/CI.yml
The previous version has been deprecated https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
> Update GitHub Actions to use upload-artifact@v4

- examples/basic_examples/Kalman filtering and smoothing.ipynb
For some reason we missed this when refactoring the examples.
> Simplify model definition in kalman filter example

- docs/src/manuals/comparison.md
- docs/src/manuals/constraints-specification.md
- docs/src/manuals/model-specification.md
- src/model/graphppl.jl
- test/ext/ProjectionExt/inference_with_projection_tests.jl
- test/inference/inference_tests.jl
- test/model/graphppl_tests.jl
- test/model/initialization_plugin_tests.jl
- test/models/aliases/aliases_gamma_tests.jl
- test/models/aliases/aliases_normal_tests.jl
Fixes #360 
This pull request includes changes to the `GraphPPL` library interface to ensure that certain distributions cannot be constructed without keyword arguments, and corresponding tests to verify this behavior.
* [`src/model/graphppl.jl`](diffhunk://#diff-66256715e7f2879d18726c887c6a1a8014325312375361e43c1fcf4eb1922d2cL242-R242): Modified the `default_parametrization` method for `Normal`, `MvNormal`, and `Gamma` to include `GraphPPL.Atomic` and an additional `rhs` parameter, ensuring these distributions cannot be constructed without keyword arguments. [[1]](diffhunk://#diff-66256715e7f2879d18726c887c6a1a8014325312375361e43c1fcf4eb1922d2cL242-R242) [[2]](diffhunk://#diff-66256715e7f2879d18726c887c6a1a8014325312375361e43c1fcf4eb1922d2cL254-R262)
* …
> Restore error message for unparametrized Normal/MvNormal/Gamma

- docs/src/manuals/model-specification.md
Fixes #359 
This pull request includes an update to the `docs/src/manuals/model-specification.md` to clarify the correct syntax for creating deterministic relationships in `RxInfer`. The most important change is the addition of a new section explaining the use of the `:=` operator for deterministic relationships.
Documentation update:
* [`docs/src/manuals/model-specification.md`](diffhunk://#diff-a8e298280fb777297db4c150dd97524a805bb77fd987a919e4b83c6f9bd31302R162-R176): Added a new section titled "Deterministic relationships" to explain the use of the `:=` operator for creating deterministic relationships between (latent) variables, with an example provided.
> Document := operator better

- docs/src/manuals/customization/custom-node.md
This pull request introduces experimental functionality for custom nodes in `RxInfer`, allowing access to node objects within message passing rules. This feature is intended for advanced scenarios and comes with performance and global state considerations.
Key changes include:
* Added a warning about the experimental nature of the new functionality and its potential changes in future releases.
* Introduced the ability to pass node references to rules, enabling inspection of the current state of other variables, implementation of complex message passing schemes, and experimentation with custom inference algorithms.
* Provided an example of how to define a custom node and enable node reference passing for it.
* Demonstrated the use of the `getnode()` function to access the node object …
> Dev node in a rule

- docs/make.jl
- docs/src/assets/chat.js
Same as in RxInferExamples.jl repository
> Try gen AI search instead

- docs/src/manuals/debugging.md
- src/inference/benchmarkcallbacks.jl
This pull request includes changes to the `RxInferBenchmarkCallbacks` structure to improve memory usage and performance tracking by using circular buffers. The most important changes include the introduction of a default buffer capacity, updates to the structure fields, and modifications to the related functions.
* [`src/inference/benchmarkcallbacks.jl`](diffhunk://#diff-f0b52774b03f1a35911b880c87d9e4113eb77b07b52cbe9725ab06e9f868da25R3-R35): Introduced `DEFAULT_BENCHMARK_CALLBACKS_BUFFER_CAPACITY` constant to set the default capacity of circular buffers used in the `RxInferBenchmarkCallbacks` structure.
* [`src/inference/benchmarkcallbacks.jl`](diffhunk://#diff-f0b52774b03f1a35911b880c87d9e4113eb77b07b52cbe9725ab06e9f868da25L44-R80): Updated the `RxInferBenchmarkCallbacks` structure …
> use circular buffer instead of vectors for benchmark stats

- docs/src/manuals/debugging.md
- src/inference/benchmarkcallbacks.jl
- test/inference/inference_tests.jl
Now exposes `__get_benchmark_stats` that exports the matrix of data to show. This can be called to gather the benchmark statistics in a julia friendly way.
> Split show for benchmarkcallbacks
